### ISSUE TITLE
small bug in tutorial

### ISSUE THREAD

**Issue by arpoe** [nextstrain/tb#5]
Hi,
I found a small bug in the tutorial on https://nextstrain.org/docs/tutorials/tb, because it throws an error with the output definition.

I think, instead of:

```
augur ancestral \
    --tree results/tree.nwk \
    --alignment results/masked.vcf.gz \
    --vcf-reference data/ref.fasta \
    --inference joint \
    --output results/nt_muts.json \
    --output-vcf results/nt_muts.vcf
```

it should say:

```
augur ancestral \
    --tree results/tree.nwk \
    --alignment results/masked.vcf.gz \
    --vcf-reference data/ref.fasta \
    --inference joint \
    --output-node-data results/nt_muts.json \
    --output-vcf results/nt_muts.vcf
```

**Comment by emmahodcroft** [comment]
Hi @arpoe ! Thanks so much for writing and letting us know about this! An oversight on our part, but you're 100% correct that the tutorial was still listing an older command than the most recent version of `augur` uses. Thanks for drawing our attention to this - I've updated it on the website just now! (Will take a few minutes to rebuild and show the change.)
Thanks again!
